### PR TITLE
Feature: add ClassicEditor, OptionsPanel, and SettingsSection components

### PR DESCRIPTION
**Pull request by glaubersilva**
## Description

This PR adds the following component to the library:

1. The `ClassicEditor` component which uses the TinyMCE editor shipped with WordPress under the hood.
2. The `OptionsPanel` component that can provide multiple arrangements to attend a variety of settings necessary in different blocks.
3. The `SettingsSection` component that is used in the new settings UI to visually separate settings into horizontal sections.

## Affects

The following add-ons:

- FFM
- Tributes
- Funds

## Visuals

image

image

## Testing Instructions

1. Pull this repository in the `wp-content/plugins` folder;
2. In the addon folder that you wish to test, go to the `package.json` file and add the following line as a dependency: `"@givewp/form-builder-library": "file:../form-builder-library/src"` and run the `npm install` command after that;
4. Go to the place in the addon codebase where one of these components is being used and replace the import line to use the component from the package installed in the previous step. 

For example, the following line: 

```
import ClassicEditor from "../ClassicEditor";
```

Should become something like this: 

```
import ClassicEditor from "@givewp/form-builder-library/ClassicEditor";
```

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Review by JasonTheAdams — APPROVED** [review]
Looks good, @glaubersilva! I just added the prettier files and such to `master`. Mind merging that in and then making sure everything is formatted properly?

**Comment by glaubersilva** [comment]
@JasonTheAdams I noticed a few problems running the `npm run dev` in the Give core and in the Funds addon after updating them to use the `OptionsPanel` component from this library/PR. 

For more details and context, check out this video: https://www.loom.com/share/6e475bea74e740ac8d43922735d38229

So, we need to understand why these errors are happening before merging it.

As a note, in the video, I was using this branch of the Funds addon: https://github.com/impress-org/give-funds/pull/125


**UPDATE:** The problem demonstrated in the video does not happen only with the `OptionsPanel` component but with all other components - `CurrencyControl` and `ClassicEditor` - from the library. So the problem seems not to be related to this PR.

**Comment by JasonTheAdams** [comment]
Hey @glaubersilva!

Oof, what a mess. Hahah! Let's break this down.

First, running `npm run dev` on GiveWP runs both the Laravel Mix dev and WP Scripts dev. Laravel Mix has strict TypeScript checking in place, while WP Scripts does not. It's annoying. Usually, the best route is to simply address the TS warnings/errors, using @ts-ignore when needed.

Second, I believe Funds is using an older version of Laravel Mix that required the Babel file — you'll notice we aren't using that on GiveWP. It may be that we just don't need that file, or updating Laravel Mix will remove the need for it.

Lastly, it looks like that `store/index.js` file _should_ be `index.jsx` since it contains JSX.

**Comment by glaubersilva** [comment]
@JasonTheAdams Thanks for the explanations. I really appreciate that cause it helped me to solve the problems in the Funds addon and now it's working as expected with this library. I also did a few tests in the FFM addon and also is working there.

However, at the Core, I'm still facing a few problems. I did use the `@ts-ignore` in the places where the Larevel Mix points out the errors, but the problem is that it still keeps pointing errors on files inside the form builder library folder as you can see on the attached screenshot. As in the addons, this problem doesn't happen, seems that it's related to some specific config at the Core, but have no idea which one. 

I also was wondering if there is a way to disable this strict mode in Laravel Mix to make it work as the WP Scripts, I've been researching about it but without success until now.

image

**Comment by glaubersilva** [comment]
@JasonTheAdams I found the solution for the Give core issue. 

All I needed to do was update these packages: 

```
"@types/react": "^18.0.27",
"@types/react-dom": "^18.0.10",
```

To these:

```
"@types/react": "^18.2.21",
"@types/react-dom": "^18.2.7",
```

After that, the `npm run dev` started working again even using the components from this library/repository.

**Comment by JasonTheAdams** [comment]
Nice, @glaubersilva! Well done! Does that mean it's all working? 😃

**Comment by JasonTheAdams** [comment]
@glaubersilva I wonder if this would be better resolved if we changed those to peer dependencies... 🤔 

Any thoughts, @jonwaldstein?

**Comment by pauloiankoski** [comment]
@glaubersilva I have performed some changes here:
- Changed ClassicEditor settings as agreed with Jeffrey;
- Added a stylesheet to each component so they carry their styles when imported;
- Added the only new component (`SettingsSection`) I need for the new UI;

Btw, another way to use these while not published to NPM is linking it to our project. Here are the steps:
- Add this repo anywhere in your computer but `node_modules`;
- Go to its root folder and run `npm link`;
- Go to the project you wanna use the library and run `npm link @givewp/form-builder-library`;

**Comment by pauloiankoski** [comment]
> image

@glaubersilva I'm facing this same issue on https://github.com/impress-org/give-pdf-receipts/pull/254 after implementing the imports from the new library. Do you have an idea about how to fix it? I've already confirmed that those packages you suggested are already updated.

**Comment by glaubersilva** [comment]
@pauloiankoski  After some time debugging it I realized that the `@types/react` and `@types/react-dom` versions from the Core and the add-ons that I changed to use this library are different. 

The proper solution is to run the `npm install --save-dev @types/react @types/react-dom` command, so it will install the proper version for the project - we don't need to set the version explicitly. I did it on your branches (PDF Receipst and Core) and everything worked as expected.

@JasonTheAdams This way, I believe that nothing more is holding up the Form Builder Library from being published.

**Pull request merged**
