### PR TITLE
Feature: deliver bundle with rollupjs

### PR DESCRIPTION
**Pull request by jonwaldstein**
## Description

This updates the package to deliver a bundled file using rollupjs including typescript definitions.

The package now also uses `peerDependencies` to require the project this is installed on to install.

## Affects

- New build process for bundled delivery

## Visuals

```
import {ClassicEditor} from 'form-builder-library';
```

## Testing Instructions

- Run `npm install && npm run build`
- Install the package locally
- Try importing & using packages like `import {ClassicEditor} from 'form-builder-library'`;

## Pre-review Checklist

-   [ ] Acceptance criteria satisfied and marked in related issue
-   [ ] Relevant `@unreleased` tags included in DocBlocks
-   [ ] Includes unit tests
-   [ ] Reviewed by the designer (if follows a design)
-   [ ] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

### CODE REVIEW

**Comment by jonwaldstein** [comment]
@glaubersilva this is ready for review!

**Review by glaubersilva — CHANGES_REQUESTED** [review]
@jonwaldstein Thanks for the improvements. Almost everything worked as expected, except the styles as the files are not getting copied to the build folder - check the screenshot for reference.

I also have a question...

Which is the proper way to import a type from this package? Would be something like this: 
```
import {OptionProps} from '@givewp/form-builder-library/build/OptionsPanel/types';
```

image

**Comment by jonwaldstein** [comment]
@glaubersilva I updated the config to use postcss for more flexibility.  it seems the 2 most common approaches are to bundle separate css file(s) or inject styles into the head tag.  I currently have it setup to use the latter, as injecting styles into the head is the simplest direction.  I think my ideal method would be to somehow preserve the importing in js and let the package handle how the styles get generated - but it doesn't seem that straightforward as the compiler removes the css imports in the final output.

Give this update a try and see if it works as expected - which is the main goal, we can always improve this part later.

As for importing types, we might want to start consolidating them into one file to make importing easier.  We can also explore using a rollup plugin to generate one file for us.  I think what you are doing is fine for now as the more important part is that our IDE is type aware from using typescript.

**Review by glaubersilva — APPROVED** [review]
@jonwaldstein Thanks for the changes and clarifications, it worked as expected. Great work! I think it's ready to be released now. 🥳

**Pull request merged**
